FROM libafl-base

# cargo-make dependency for example fuzzers
RUN cargo install --no-default-features --force cargo-make

# Install necessary cross compiler for libafl_qemu (if needed)
WORKDIR /
RUN apt update && apt install -y ninja-build libc6-dev-armel-cross vim
RUN wget -qO- https://musl.cc/arm-linux-musleabihf-cross.tgz | tar xzf -

# Copy in missing file for libafl_qemu and libafl_sugar
COPY libafl_qemu /libafl/libafl_qemu
COPY libafl_sugar /libafl/libafl_sugar
COPY libafl_nyx /libafl/libafl_nyx
COPY libafl_concolic /libafl/libafl_concolic
RUN cd /libafl/libafl_nyx && ./build_nyx_support.sh

# Pull down qemu fork
RUN git clone https://github.com/AFLplusplus/qemu-libafl-bridge /qemu-libafl-bridge
RUN cd /qemu-libafl-bridge && scripts/git-submodule.sh update \ 
	ui/keycodemapdb meson tests/fp/berkeley-testfloat-3 tests/fp/berkeley-softfloat-3
ENV CUSTOM_QEMU_DIR /qemu-libafl-bridge

# Build qemu with gcc because clang causes bugs here
ENV CROSS_CC=/arm-linux-musleabihf-cross/bin/arm-linux-musleabihf-gcc
RUN cd libafl/libafl_qemu && CC=gcc cargo build --release -F usermode,arm

# Download crates
WORKDIR /libafl
RUN cargo vendor /libafl-cargo >> ~/.cargo/config.toml

RUN apt install -y cmake

# When building fuzzers, use `cargo build --offline`
